### ISSUE TITLE
Fast reconnection won't accept Shout to work properly

### ISSUE THREAD

**Issue by DanielB70** [interpretor/zyre.js#21]
Hi, From the look at it , reconnecting into a group isn't working properly. DGRAM and resuse UDP socket seems to have unexpected behavior althought the whole pair connect/on connect is working, as well as join/on join.

However, whisper isn't working while responding to a onshout , we need a huge workaround to not loose any message ... 
Issue as been encounterd on Windows Server , Linux Centos and Cloud Azure Linux Centos. 
I followed the pattern Sender A (Shout) -> Recv B (On Shoot)  -> Recv (B) Whisper -> Sender A (OnWhisper )

**Comment by interpretor** [comment]
Hi @DanielB70,
can you please provide some sample code which reproduces the issue?

**Comment by DanielB70** [comment]
// UNIT TEST ENTRY
if (typeof arguments[0] != 'string') {
    const fs = require('fs');
    const ph = require('path');

    eval('var global, flow, node;');

    global = {
        get: function (propname) {
            return this[propname];
        },
        set: function (propname, value) {
            this[propname] = value;
        }
    }
}

var process_exit_cb = [];

var thirdparties = global.get('nrgsm_dependancies');
if (thirdparties == undefined) thirdparties = ['fs', 'path', 'os', 'zyre.js',
'html-entities', 'xml2js', 'util', 'chokidar', 'crypto',
'math-float32-from-bits'];
for (var t in thirdparties) {
    try {
        if (global.get(thirdparties[t]) == undefined) {
            var es = require(thirdparties[t]);
            console.log(thirdparties[t] + '...ok');
            global.set(thirdparties[t], es);
        }
    } catch (err) {
        try {
            es = require('./lib/node_modules/' + thirdparties[t]);
            console.log(thirdparties[t] + '...ok');
            global.set(thirdparties[t], es);
        } catch (Err) {
            try {
                es = require('../lib/node_modules/' + thirdparties[t]);
                console.log(thirdparties[t] + '...ok');
                global.set(thirdparties[t], es);
            } catch (errr) {
                console.log('fail to load ' + thirdparties[t])
            }
        }
    }
}

const ehternet = /^[Ee]th/;
const listInterfaces = global.get('os').networkInterfaces();
var ipenv = 29;
for (var inter in listInterfaces) {
    if (ehternet.test(inter))
        for (var van in listInterfaces[inter]) {
            if ((listInterfaces[inter][van].internal == false) && (
listInterfaces[inter][van].family == 'IPv4')) {
                ipenv = /\d+\.(\d+)\.\d+\.\d+/.exec(listInterfaces[inter][
van].address)[1];
                global.set('NRGSM_CORE_NUI', listInterfaces[inter][van].
address);
                global.set('NRGSM_CORE_ETH', inter);
                break;
            }
        }
}
global.set('NRGSM_CORE_ENV', ipenv)
console.log(ipenv);

const Zyre = global.get('zyre.js');

var zyre;
const zyre_LINGER = 1000;

var zyre_name;
var zyre_array_req;
var zyre_seqNumber = 0;
var zyre;
var zyre_shoutpending = {}

function zyrefactory() {
    var eth = global.get('NRGSM_CORE_ETH');
    var dt = +new Date();

    if (zyre != undefined) zyre.stop();
    try {
        zyre = new Zyre({
            name: zyre_name + dt, // Name of the zyre node
            iface: eth, // Network interface
            headers: { // Headers will be sent on every new connection
                haccid: zyre_name,
            },
            evasive: 20 * zyre_LINGER, // Timeout after which the local
node will try to ping a not responding peer
            expired: 60 * zyre_LINGER, // Timeout after which a not
responding peer gets disconnected
            port: 53651, // Port for incoming messages, will be incremented
if already in use
            bport: 53650, // Discovery beacon broadcast port
            binterval: zyre_LINGER, // Discovery beacon broadcast interval
        });
    } catch (unbale) {
        throw 'Error ZRE protocole, fail to create new Zyre point';
    }
    zyre.pending = {};
    zyre.behaviors = {};
    zyre.wait4connected = true;

    if (!Array.isArray(zyre_array_req)) throw 'arg1 expected to be
[{topic=string, init=function(msg), onRequestCb= function(msg) }] ';
    for (var a in zyre_array_req) {
        if ((zyre_array_req[a].topic == undefined)
            || (['shared', 'request'].indexOf(zyre_array_req[a].type) < 0)
            || (typeof (zyre_array_req[a].init) != 'function')
            || (typeof (zyre_array_req[a].onRequestCb) != 'function'))
throw 'config
for shared topic :' + zyre_array_req[a].topic + ' required {topic=string,
init=function(msg), onRequestCb= function(msg) }';

        zyre.behaviors[zyre_array_req[a].topic] = zyre_array_req[a];
    }
    return zyre;
}

function zyre_Listener() {
    var groups = {}
    for (var topic in zyre.behaviors) {
        groups[topic] = true;
    }
    var retry = 500;
    var hLoop;
    (function loop() {
        setTimeout(() => {
            retry = 60000;
            var t = 0, g = 0;
            for (var topic in groups) {
                g++;
                try {
                    zyre.join(topic);
                    delete groups[topic];
                    t++;
                } catch (_) {
                    console.log('ZRE cluster:' + topic + ' dial again..')
                }
            }
            if (t != g) loop();
        }, retry);
    })();
    var Hwnd = setInterval(() => {
        var handle = Hwnd;
        var dts = Math.floor(new Date().getTime() / 1000);
        for (var z in zyre_shoutpending) {
            try {
                if (dts - zyre_shoutpending[z][2] > 60) {
                    zyre_shoutpending[z][2]=dts;
                } else if (dts - zyre_shoutpending[z][2] > 10) {
                } else if (dts - zyre_shoutpending[z][2] > 0) {
                    zyre.whisper(zyre_shoutpending[z][0], zyre_shoutpending[
z][1]);
//                  process.exit(0);
//
//                  clearInterval(handle);
//                  groups = {};
//                  zyre = zyrefactory();
//                  zyre.start(zyre_Listener);
//                  break;
//              }
            } catch (_) {
                console.log(_)
            }
        }
    }, 500);
}
function zyre_subscribe(str_name, array_request) {
    zyre_name = str_name;
    zyre_array_req = array_request;

    zyre = zyrefactory();

    zyre.on('connect', () => {
        if (zyre.wait4connected) zyre.wait4connected = false;

        for (var z in zyre.pending)
            if (zyre.behaviors[z] != undefined && zyre.pending[z]) {
                zyre.behaviors[z].init(z);
                zyre.pending[z] = false;
            }
    });

    zyre.on('join', (id, name, topic) => {
        console.log(['join', id, name])
        if (zyre.pending[topic] == undefined) zyre.pending[topic] = true;
    });
    zyre.on('leave', (id, name, topic) => {
        console.log(id + ' leaving')
    });
    zyre.on('expired', (id, name) => {
        console.log(id + ' expired')
    });
    zyre.on('disconnect', (id, name) => {
    });

    zyre.on('shout', (id, name, message, topic) => {
        console.log(['shout', id, name])
        var pi = message.indexOf('¤NRG¤');
        var mess = message.substr(0, pi)
        var seqNumberAnswer = message.substr(pi + 5);
        if (zyre.behaviors[topic] != undefined) {
            var nsg;
            try {
                nsg = JSON.parse(mess)
            } catch (_) {
                nsg = { payload: mess }
            }
            (function () {
                var topic_init = topic;
                nsg.resp = {
                    send: function (msg, topic) {
                        if (topic == topic_init) {
                            var ret;
                            try {
                                var mesg = (typeof msg != 'string') ? JSON.
stringify(msg) : msg;
                                mesg = mesg + '¤NRG¤' + topic + '¤' +
seqNumberAnswer;
                                var dts = new Date().getTime()/1000;

                                zyre_shoutpending[seqNumberAnswer] = [ id,
mesg + '¤NRG¤' + topic + '¤' + seqNumberAnswer, dts];

                            } catch (_) {
                                console.log(_)
                            }
                            return ret;

                        }
                    }
                }
                zyre.behaviors[topic].onRequestCb(nsg);
            })();
        }
    });

    zyre.on('whisper', (id, name, message) => {
        var nsg, topic = 'nrgsm.cache', pi = message.indexOf('¤NRG¤'), mess,
seq = message.indexOf('¤', pi + 6), seqNumber;
        if (pi > 0) {
            seqNumber = message.substring(seq + 1);
            topic = message.substring(pi + 5, seq);
            mess = message.substr(0, pi);
        } else mess = message;

        try {
            nsg = JSON.parse(mess)
        } catch (_) {
            nsg = { payload: mess }
        }
        nsg.resp = null;

        try {
            zyre.behaviors[topic].onRequestCb(nsg)
        } catch (err) {
            console.log(err);
        }
    });

    process_exit_cb.push(function () {
        zyre.stop(() => { });
    });

    var mom = {
        zyre: zyre,
        send: function (msg, topic) {
            var packmsg;
            if (typeof msg != 'string') packmsg = JSON.stringify(msg);
            else packmsg = msg;

            // No Loss Message while other reboot
            zyre.shout(topic, packmsg + '¤NRG¤' + zyre_seqNumber );
            zyre_seqNumber++;
        }
    }
    zyre.start(zyre_Listener);

    return mom;
}
global.set('NRGSM_LINKS', zyre_subscribe);



if (typeof arguments[0] != 'string') {

    setTimeout(() => {
        var mom = global.get('NRGSM_LINKS')('unitest', [
            {
                type: 'shared', topic: 'nrgsm.haccid',
                init: (msg) => { console.log('test') },
                onRequestCb: (msg) => { console.log('test2') },
            },
            {
                type: 'request', topic: 'nrgsm.cache',
                init: (msg) => { console.log('test4') },
                onRequestCb: (msg) => { console.log('test5') },
            },
        ]);
    }, 1000);
}

function gracefull_exit() {

    for (var p in process_exit_cb) try { process_exit_cb[p](); } catch (_)
{ }
    process.exit(0);
}
global.set('PRC_GRACEFULL', process_exit_cb);

process.on('SIGINT', gracefull_exit);
process.on('SIGTERM', gracefull_exit);



Le mar. 26 févr. 2019 à 13:41, Sebastian Rager <notifications@github.com> a
écrit :

**Comment by DanielB70** [comment]
Hi, this is a full code test that reproduce the problem... I tested
multiple version, there is no hope, reconnecting too fast will make the
paire onshout/whisper fail ...

Worst, creating multiple connecter on the same machine, will generate a
DRGAM not running

Le mar. 26 févr. 2019 à 16:25, Daniel BOUTRIN <daniel.boutrin@gmail.com> a
écrit :

**Comment by interpretor** [comment]
If your issue is still present, please test the new beta version which uses the rewritten version of zeromq.js:

```bash
npm install zyre.js@beta
```

[Beta Branch](https://github.com/interpretor/zyre.js/tree/beta)

**Comment by DanielB70** [comment]
Omg hi,

It's been a long time, I will give it a look I am currently planning to use
in Node-Red ... I made a lot of work around it ... Thanks

Le mar. 17 mars 2020 à 22:04, Sebastian Rager <notifications@github.com> a
écrit :
