### ISSUE TITLE
iface selection

### ISSUE THREAD

**Issue by Zulu-Inuoe** [interpretor/zyre.js#28]
I've noticed the behaviour of `iface` is, to me, surprising.

From the [Zyre reference implementation in C](https://github.com/zeromq/zyre/blob/5c30222035597a73b1ef92d2572bdf92e9085201/include/zyre.h#L104) :
```c
//  Set network interface for UDP beacons. If you do not set this, CZMQ will
//  choose an interface for you. On boxes with several interfaces you should
//  specify which one you want to use, or strange things can happen.
//  The interface may by specified by either the interface name e.g. "eth0" or
//  an IP address associalted with the interface e.g. "192.168.0.1"
ZYRE_EXPORT void
    zyre_set_interface (zyre_t *self, const char *value);
```

Note that we can specify IP address.

However, looking at the algorithm used in zyre.js, it only accepts the interface name.

My desire is, on Windows, to supply `127.0.0.1` to denote the loopback adapter 'pseudo interface'.
I'm willing to make the change & PR but wanted to clarify this.

Additionally, even if I do supply the adapter name, I run into the situation where the code fails to accept it because it is marked as 'internal'

![image](https://user-images.githubusercontent.com/1526310/183140982-82d9d671-cfe1-4b43-aa31-05cb86dc6439.png)

Note the adapter is marked as private.
The code has the logic of declining to use nay with `.internal` being truthy.
This makes sense to me if the user did not explicitly supply an adapter (select the first public iface). But if they specify an adapter, what does it matter if it's public/private?

I'd appreciate any thoughts!

**Comment by interpretor** [comment]
Good find, thank you.
I changed the behavior, it should behave now similar to the Zyre implementation in C.
