### ISSUE TITLE
Lost JOIN messages

### ISSUE THREAD

**Issue by Dev1an** [interpretor/zyre.js#6]
**When**
- I try to monitor `'join'` events on a network with a zyre.js node (1) and
- I create another node (2) that joins a group (A) right after I start node (2)
- (node (2) starts after node (1) is started)

**then**
 - node (1) does not emit a `'join'` to indicate that node (2) joined group (A).

I think this is a bug because when I ask node (1) information about group (A) some time later, it says node (1) did join the group (even though it did not emit the `'join'` event).

I can replicate this using the following code on my macbook:

```js
const Zyre = require('zyre.js')
const testGroup = 'testGroup'

const node1 = Zyre.new({name: 'Node 1'})
const node2 = Zyre.new({name: 'Node 2'})

node1.on('join', (id, name, group)=> {
	console.log(name, 'joined', group)
})

node1.start(() => {
	node1.join(testGroup) // this line is not necessary to reproduce the bug

	node2.start(() => {
		node2.join(testGroup)
	})
})

setTimeout(function () {
	console.log(node1.getGroup(testGroup))
}, 2000)
```

**Comment by interpretor** [comment]
Fixed: https://github.com/interpretor/zyre.js/commit/7968b4c7a66f38d6733c6f41018aa6326dfd9e35
